use crate::wad::{get_lump_data, DoomFile};
use std::default::Default;
use std::rc::Rc;

pub struct SoundEffect {
    // six chars
    pub name: String,
    pub lump_name: String,
    pub singularity: bool,
    pub priority: u32,
    pub link: Option<SoundEffectLink>,
    pub data: Option<Vec<u8>>,
    pub usefulness: u32,
}

pub struct SoundEffectLink {
    pub sound_effect: Rc<SoundEffect>,
    pub pitch: u32,
    pub volume: u32,
}
impl Default for SoundEffect {
    fn default() -> Self {
        Self {
            name: String::new(),
            lump_name: String::new(),
            singularity: false,
            priority: 0,
            link: None,
            data: None,
            usefulness: 0,
        }
    }
}
pub struct Music {
    // 6 chars
    pub name: String,
    pub data: Vec<u8>,
    pub handle: u32,
}

pub fn start_music(music_name: String) {}

pub fn start_sound(sound_name: &str, mut doom_files: Vec<DoomFile>) {
    let sound_lump: Vec<u8> = get_lump_data(&mut doom_files, "DSPISTOL");
    let sounds: Vec<SoundEffect> = vec![
        SoundEffect {
            name: String::from("pistol"),
            singularity: false,
            priority: 64,
            link: None,
            ..Default::default()
        },
        SoundEffect {
            name: String::from("shotgn"),
            singularity: false,
            priority: 64,
            link: None,
            ..Default::default()
        },
        SoundEffect {
            name: String::from("sgcock"),
            singularity: false,
            priority: 64,
            link: None,
            ..Default::default()
        },
        SoundEffect {
            name: String::from("dshtgn"),
            singularity: false,
            priority: 64,
            link: None,
            ..Default::default()
        },
        // SoundEffect{name: String::from( "dbopn"), false, 64, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "dbcls"), false, 64, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "dbload"), false, 64, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "plasma"), false, 64, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bfg"), false, 64, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "sawup"), false, 64, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "sawidl"), false, 118, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "sawful"), false, 64, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "sawhit"), false, 64, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "rlaunc"), false, 64, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "rxplod"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "firsht"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "firxpl"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "pstart"), false, 100, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "pstop"), false, 100, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "doropn"), false, 100, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "dorcls"), false, 100, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "stnmov"), false, 119, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "swtchn"), false, 78, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "swtchx"), false, 78, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "plpain"), false, 96, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "dmpain"), false, 96, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "popain"), false, 96, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "vipain"), false, 96, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "mnpain"), false, 96, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "pepain"), false, 96, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "slop"), false, 78, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "itemup"), true, 78, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "wpnup"), true, 78, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "oof"), false, 96, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "telept"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "posit1"), true, 98, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "posit2"), true, 98, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "posit3"), true, 98, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bgsit1"), true, 98, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bgsit2"), true, 98, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "sgtsit"), true, 98, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "cacsit"), true, 98, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "brssit"), true, 94, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "cybsit"), true, 92, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "spisit"), true, 90, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bspsit"), true, 90, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "kntsit"), true, 90, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "vilsit"), true, 90, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "mansit"), true, 90, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "pesit"), true, 90, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "sklatk"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "sgtatk"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "skepch"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "vilatk"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "claw"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "skeswg"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "pldeth"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "pdiehi"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "podth1"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "podth2"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "podth3"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bgdth1"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bgdth2"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "sgtdth"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "cacdth"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "skldth"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "brsdth"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "cybdth"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "spidth"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bspdth"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "vildth"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "kntdth"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "pedth"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "skedth"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "posact"), true, 120, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bgact"), true, 120, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "dmact"), true, 120, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bspact"), true, 100, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bspwlk"), true, 100, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "vilact"), true, 100, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "noway"), false, 78, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "barexp"), false, 60, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "punch"), false, 64, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "hoof"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "metal"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "chgun"), false, 64, &S_sfx[sfx_pistol], 150, 0, 0 },
        // SoundEffect{name: String::from( "tink"), false, 60, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bdopn"), false, 100, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bdcls"), false, 100, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "itmbk"), false, 100, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "flame"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "flamst"), false, 32, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "getpow"), false, 60, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bospit"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "boscub"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bossit"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bospn"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "bosdth"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "manatk"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "mandth"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "sssit"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "ssdth"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "keenpn"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "keendt"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "skeact"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "skesit"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "skeatk"), false, 70, 0, -1, -1, 0 },
        // SoundEffect{name: String::from( "radio"), false, 60, 0, -1, -1, 0 }
    ];
}

// Name, lumpnum, data, handle
//{ "e1m1", 0 },
//{ "e1m2", 0 },
//{ "e1m3", 0 },
//{ "e1m4", 0 },
//{ "e1m5", 0 },
//{ "e1m6", 0 },
//{ "e1m7", 0 },
//{ "e1m8", 0 },
//{ "e1m9", 0 },
//{ "e2m1", 0 },
//{ "e2m2", 0 },
//{ "e2m3", 0 },
//{ "e2m4", 0 },
//{ "e2m5", 0 },
//{ "e2m6", 0 },
//{ "e2m7", 0 },
//{ "e2m8", 0 },
//{ "e2m9", 0 },
//{ "e3m1", 0 },
//{ "e3m2", 0 },
//{ "e3m3", 0 },
//{ "e3m4", 0 },
//{ "e3m5", 0 },
//{ "e3m6", 0 },
//{ "e3m7", 0 },
//{ "e3m8", 0 },
//{ "e3m9", 0 },
//{ "inter", 0 },
//{ "intro", 0 },
//{ "bunny", 0 },
//{ "victor", 0 },
//{ "introa", 0 },
//{ "runnin", 0 },
//{ "stalks", 0 },
//{ "countd", 0 },
//{ "betwee", 0 },
//{ "doom", 0 },
//{ "the_da", 0 },
//{ "shawn", 0 },
//{ "ddtblu", 0 },
//{ "in_cit", 0 },
//{ "dead", 0 },
//{ "stlks2", 0 },
//{ "theda2", 0 },
//{ "doom2", 0 },
//{ "ddtbl2", 0 },
//{ "runni2", 0 },
//{ "dead2", 0 },
//{ "stlks3", 0 },
//{ "romero", 0 },
//{ "shawn2", 0 },
//{ "messag", 0 },
//{ "count2", 0 },
//{ "ddtbl3", 0 },
//{ "ampie", 0 },
//{ "theda3", 0 },
//{ "adrian", 0 },
//{ "messg2", 0 },
//{ "romer2", 0 },
//{ "tense", 0 },
//{ "shawn3", 0 },
//{ "openin", 0 },
//{ "evil", 0 },
//{ "ultima", 0 },
//{ "read_m", 0 },
//{ "dm2ttl", 0 },
//{ "dm2int", 0 }
